// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyType } from "./KeyType";

export interface Key { key: string, title: string, description: string, keyType: KeyType, path: string | null, command: string | null, imagePath: string | null, }