// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Preferences { shortcut: string, launch_on_login: boolean, menu_bar_icon: boolean, }